const mongoose = require('mongoose')

const objectArray = new mongoose.Schema({
    id: Number,
    isActive: Boolean,
    row: Number,
    type: String,
    note: String,
    backgroundColor: String
})

const user = new mongoose.Schema({
    username: String,
    password: String,
    hihatArray: [[objectArray]],
    openHhArray: [[objectArray]],
    kickArray: [[objectArray]],
    snareArray: [[objectArray]],
    melodyRowOne: [[objectArray]],
    melodyRowTwo: [[objectArray]],
    melodyRowThree: [[objectArray]],
    melodyRowFour: [[objectArray]],
    melodyRowFive: [[objectArray]],
    melodyRowSix: [[objectArray]],
    melodyRowSeven: [[objectArray]],
    melodyRowEight: [[objectArray]],
    melodyRowNine: [[objectArray]],
    melody2RowOne: [[objectArray]],
    melody2RowTwo: [[objectArray]],
    melody2RowThree: [[objectArray]],
    melody2RowFour: [[objectArray]],
    melody2RowFive: [[objectArray]],
    melody2RowSix: [[objectArray]],
    melody2RowSeven: [[objectArray]],
    melody2RowEight: [[objectArray]],
    melody2RowNine: [[objectArray]],
    bassRowOne: [[objectArray]],
    bassRowTwo: [[objectArray]],
    bassRowThree: [[objectArray]],
    bassRowFour: [[objectArray]],
    bassRowFive: [[objectArray]],
    bassRowSix: [[objectArray]],
    bassRowSeven: [[objectArray]],
    bassRowEight: [[objectArray]],
    bassRowNine: [[objectArray]],
    receivedhihatArray: [[objectArray]],
    receivedopenHhArray: [[objectArray]],
    receivedkickArray: [[objectArray]],
    receivedsnareArray: [[objectArray]],
    receivedmelodyRowOne: [[objectArray]],
    receivedmelodyRowTwo: [[objectArray]],
    receivedmelodyRowThree: [[objectArray]],
    receivedmelodyRowFour: [[objectArray]],
    receivedmelodyRowFive: [[objectArray]],
    receivedmelodyRowSix: [[objectArray]],
    receivedmelodyRowSeven: [[objectArray]],
    receivedmelodyRowEight: [[objectArray]],
    receivedmelodyRowNine: [[objectArray]],
    receivedmelody2RowOne: [[objectArray]],
    receivedmelody2RowTwo: [[objectArray]],
    receivedmelody2RowThree: [[objectArray]],
    receivedmelody2RowFour: [[objectArray]],
    receivedmelody2RowFive: [[objectArray]],
    receivedmelody2RowSix: [[objectArray]],
    receivedmelody2RowSeven: [[objectArray]],
    receivedmelody2RowEight: [[objectArray]],
    receivedmelody2RowNine: [[objectArray]],
    receivedbassRowOne: [[objectArray]],
    receivedbassRowTwo: [[objectArray]],
    receivedbassRowThree: [[objectArray]],
    receivedbassRowFour: [[objectArray]],
    receivedbassRowFive: [[objectArray]],
    receivedbassRowSix: [[objectArray]],
    receivedbassRowSeven: [[objectArray]],
    receivedbassRowEight: [[objectArray]],
    receivedbassRowNine: [[objectArray]],
    name: Array,
    author: Array
})



module.exports = mongoose.model("User", user) 